### ISSUE TITLE
Can we add relevant experiments for attention mechanism proposed in PVT?

### ISSUE THREAD

**Issue by hailong23-jin** [CreamNuts/Fair-Comparison-between-Efficient-Attentions#1]
Thanks for the excellent work. In this paper for linear Attention ,  we chose LinFormer for comparation. However LinFormer is firstly designed for NLP tasks. In CV fields, under the same thought, it will be better to use convolution instead of linear layer. PVT and PVT v2 can be used as reference. 

Furthermore, just as a suggestion, A very recent work titled "Separable Self-attention for Mobile Vision Transformers" proposed separable attention, a new efficient attention mechanism. I will be very grateful if we could add the relevant experiments.

**Comment by CreamNuts** [comment]
Thanks for your interest. 

I want to add all relevant experiments about efficient attention. But we have limited gpu resource and ImageNet1K is large dataset, so we can't afford to do additional experiment.
